### ISSUE TITLE
Header doesn't mix well with no-banner pages.

### ISSUE THREAD

**Issue by nmorduch** [littleweaver/littleweaverweb.com#31]
:/ Like on all widths with no banner :( :(

I think the best approach to fixing this would be making all pages have banners.

**Comment by harrislapiroff** [comment]
I don't want to force obligatory banners—partially because I want this design to be flexible enough to accommodate a variety of layouts and partially because I do still think some pages with banners (esp. blog posts that don't have images) will feel pretty forced. I fixed this in 9cfc28b537914abf7f3ee166b9d24a541e1b8348 and cce4491fbc2173fe9712f86126254be8015b602f by cutting off the nest part of the logo in xs to make it shorter and by adding a left margin to pages without banners on sm.

![screen shot 2016-02-03 at 12 43 03](https://cloud.githubusercontent.com/assets/296631/12791152/afec4af8-ca73-11e5-8e9c-8325bb2cc989.png)

![screen shot 2016-02-03 at 12 42 57](https://cloud.githubusercontent.com/assets/296631/12791155/b224d4de-ca73-11e5-8816-5f16b44aa10e.png)
